spring:
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: validate
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 1234
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true